[book]
authors = ["sqyyy", "Skienex"]
language = "de"
src = "src"
title = "Liquip Dokumentation"
description = "Das Liquip Buch behandelt alle Features des Liquip-Plugins."

[output.html]
mathjax-support = true
site-url = "/docs-de/"
git-repository-url = "https://github.com/liquip/docs-de"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2